---
- name: Provision synapse container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Project configuration
    - "{{ playbook_dir }}/../../configuration/configuration_{{ host_id }}.yml"
    # Coturn configuration
    - "{{ playbook_dir }}/../../../ryo-coturn/configuration/coturn_static_auth_secret_{{ host_id }}.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-consul
    - role: install-synapse
    - role: set-up-firewall-synapse
    - role: set-up-consul
    - role: set-up-synapse
