---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Provision element-web container image
  hosts: packer

  vars_files:
    # Project configuration
    - "{{ playbook_dir }}/../../configuration/configuration_{{ host_id }}.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-rsyslog
    - role: install-consul
    - role: install-nginx
    - role: set-up-firewall-element
    - role: set-up-consul
    - role: set-up-element-web
