---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Provision synapse-admin container image
  hosts: packer
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Project configuration
    - "{{ playbook_dir }}/../../configuration/configuration_{{ host_id }}.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"

  roles:
    - role: upgrade-container
    - role: install-nftables
    - role: install-rsyslog
    - role: install-consul
    - role: install-nginx
    - role: install-synapse-admin
    - role: set-up-firewall-synapse-admin
    - role: set-up-consul
    - role: set-up-synapse-admin
