---
## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ project_id }}"
    state: directory
    mode: '0755'

### Synapse directories

- name: Create a directory for synapse content
  file:
    path: "/var/containers/{{ project_id }}/synapse"
    state: directory
    mode: '0755'

- name: Create a directory for synapse config
  file:
    path: "/var/containers/{{ project_id }}/synapse/config"
    state: directory
    mode: '0755'

- name: Create a directory for synapse data
  file:
    path: "/var/containers/{{ project_id }}/synapse/data"
    state: directory
    mode: '0755'
