---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Make sure unattended-upgrades package is uninstalled and purged
  apt:
    name: unattended-upgrades
    update_cache: no
    purge: yes
    state: absent

- name: Update package cache and ensure all packages are updated
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Autoremove unused packages
  apt:
    autoremove: yes

